

function checkQ1() {

	if (document.question1.question.value == "c") {
		document.getElementById("after_submitQ1").style.visibility = "visible";
		document.getElementById("answerQ1").innerHTML = "Correct!! <br><br>The EEG measures the difference in voltage between two points.<br><br>In particular, voltage is the difference in electrical potential between two points. <b>There is no absolute voltage for a single point</b>. Voltage is always the difference in electrical potential between points.<br><br>In the EEG this translates into voltage being the difference between two contiguous electrodes (in a bipolar montage) or between an electrode of interest and some reference electrode or reference group of electrodes (in a referential montage).";
		document.getElementById("after_submitQ1").style.background = "lightgreen";
		document.getElementById("afterQ1_picture").innerHTML = "Great job!";

}	else {
		document.getElementById("after_submitQ1").style.visibility = "visible";
		document.getElementById("answerQ1").innerHTML = "Think about what do you see in an EEG.<br><br>Do you see values for single electrodes or do you see two different electrodes being compared?<br><br>In which units are the vertical deflections on EEG measured?";
		document.getElementById("after_submitQ1").style.background = "red";
		document.getElementById("afterQ1_picture").innerHTML = "Try again!";

}

}








function checkQ2() {

	if (document.getElementById("q2a").checked == true && document.getElementById("q2b").checked == true && document.getElementById("q2c").checked == true && document.getElementById("q2d").checked == true && document.getElementById("q2e").checked == false) {
		document.getElementById("after_submitQ2").style.visibility = "visible";
		document.getElementById("answerQ2").innerHTML = "Correct! <br><br>The nose, the ears, or the back of the neck are good references because they typically do not have muscle artifact or movement artifact and do not pick brain activity: they are relatively quiet.<br><br>The average of all electrodes of the head are also a good reference because they cancel out deflections in one or other direction from the different electrodes and result in a pretty quiet reference.<br><br>A precordial electrode picks up the electrical activity of the heart (which is of a much higher voltage than that of the brain) and, therefore, it is a 'contaminated' reference.";
		document.getElementById("after_submitQ2").style.background = "lightgreen";
		document.getElementById("afterQ2_picture").innerHTML = "Great job!";

	} else {
		document.getElementById("after_submitQ2").style.visibility = "visible";
		document.getElementById("answerQ2").innerHTML = "Not correct.";
		document.getElementById("after_submitQ2").style.background = "red";
		document.getElementById("afterQ2_picture").innerHTML = "Make sure you check all the correct answers and uncheck all the incorrect answers.<br><br>Try again!";

}


}








function checkQ3() {

	if (document.question3.question.value == "b") {
		document.getElementById("after_submitQ3").style.visibility = "visible";
		document.getElementById("answerQ3").innerHTML = "Correct!! <br><br>The electrical activity generated in the brain is tiny (in the order of microvolts). That is several orders of magnitude smaller than the electrical activity generated in the heart or in machines around the patient (in the order of millivolts).<br><br>The frequencies generated by electrical activity in the brain substantially overlap with the frequencies generated in the heart or in other electrical noise around the patient.<br><br>The obvious question then is: how are we able to measure the tiny electrical activity from the brain at all?<br><br>Well, the answer is again related to a difference in voltage. The electrodes on the scalp are close to the brain and there is a voltage difference between different brain regions, even when these voltage differences are tiny. In contrast, the electrical activity coming from far away arrives at the head with approximately the same strength. Therefore, the electrical current picked up by each electrode on the scalp is the same and there is no voltage difference between electrodes (noise cancels out).";
		document.getElementById("after_submitQ3").style.background = "lightgreen";
		document.getElementById("afterQ3_picture").innerHTML = "Great job!";

}	else {
		document.getElementById("after_submitQ3").style.visibility = "visible";
		document.getElementById("answerQ3").innerHTML = "Think about voltage differences.";
		document.getElementById("after_submitQ3").style.background = "red";
		document.getElementById("afterQ3_picture").innerHTML = "Try again!";

}

}








function checkQ4() {

	if (document.question4.question.value == "b") {
		document.getElementById("after_submitQ4").style.visibility = "visible";
		document.getElementById("answerQ4").innerHTML = "Correct!! <br><br>The model above is a major oversimplification of reality. Apart from excitatory postsynaptic potentials there are inhibitory postsynaptic potentials. Also, neurons are not always perpendicularly oriented to the surface of the brain. Further, the surface of the brain is not always perpendicularly oriented to the surface of the scalp (there are sulci and fissures). And the brain is definitively not a perfect sphere. In summary, the conclusion that the maximum negativity on scalp EEG marks the area of the brain where negative deflections come from is a major oversimplification of reality: it works fine many times so that it is a useful rule of thumb, but remember that it is just a convenient rule of thumb and it fails many times. If localization is crucial, you will need to find somebody who does <a href='https://pubmed.ncbi.nlm.nih.gov/31019487/' target='_blank'>source localization</a>.<br><br>However, if you think that the brain is a perfect sphere and all cortical neurons are perfectly perpendicular to the surface of the brain, by all means, please create your own conspiracy theory, recruit hundreds of like-minded people on the internet, and organize regular demonstrations with absurd messages on big protest signs. We are in the twenty-first century and there has never been a better time for laughing.";
		document.getElementById("after_submitQ4").style.background = "lightgreen";
		document.getElementById("afterQ4_picture").innerHTML = "Great job!";

}	else {
		document.getElementById("after_submitQ4").style.visibility = "visible";
		document.getElementById("answerQ4").innerHTML = "Well,...I hope you accidentally clicked that answer. Otherwise, please review your anatomy.";
		document.getElementById("after_submitQ4").style.background = "red";
		document.getElementById("afterQ4_picture").innerHTML = "Try again!";

}

}








function checkQ5() {

	if (document.getElementById("q5a").checked == true && document.getElementById("q5b").checked == true && document.getElementById("q5c").checked == true && document.getElementById("q5d").checked == true && document.getElementById("q5e").checked == true) {
		document.getElementById("after_submitQ5").style.visibility = "visible";
		document.getElementById("answerQ5").innerHTML = "Exactly! <br><br>There appears to be a phase reversal at P7, ...and at C3,...and at F8. If you picture the appearance of that on the scalp it looks like the figure below:";
		document.getElementById("after_submitQ5").style.background = "lightgreen";
		document.getElementById("answerQ5_picture").src = "EEG15_img/Q5.2.png";
		document.getElementById("afterQ5_picture").innerHTML = "That does not look very physiological. Also, pay attention that in each phase reversal, the negativity only affects a few electrodes around the phase reversal (rather than progressively diminishing over a broader field affecting more electrodes).<br><br>Localization does not only help you localize activity on EEG. It also helps you identify artifacts on EEG.<br><br>The fields in this EEG segment of EEG do not make sense, which should make you think of a non-brain origin for the rhythmic activity. This patient was having chest PT and the rhythmic deflections are artifact, not seizures.<br><br>Other people may be tricked into believing that that was a seizure, but not you as you now know how to localize!<br><br>Great job!";


	} else {
		document.getElementById("after_submitQ5").style.visibility = "visible";
		document.getElementById("answerQ5").innerHTML = "Not correct.";
		document.getElementById("after_submitQ5").style.background = "red";
		document.getElementById("answerQ5_picture").src = "";
		document.getElementById("afterQ5_picture").innerHTML = "Make sure you check all the correct answers and uncheck all the incorrect answers.<br><br>Try again!";

}


}



